name: evportable
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment: 
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  flutter_downloader: ^1.4.3
  common_utils: ^1.2.1
  firebase_analytics: ^5.0.11
  fish_redux: ^0.3.4  
  firebase_messaging: ^6.0.13
  shared_preferences: ^0.5.3+4
  lottie: ^0.7.0+1
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.2.0
  firebase_storage: ^3.1.3  
  dio: ^3.0.9
  dio_http_cache: ^0.2.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  permission_handler: ^3.2.2
  font_awesome_flutter: ^8.5.0
  #video_player: ^0.10.5+2
  #flutter_inappwebview: ^3.4.0+2
  path_provider: ^1.3.0
  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^1.4.4+1
  cached_network_image: ^2.0.0
  fluttertoast: ^7.0.2
  photo_view: ^0.8.0
  parallax_image: ^0.3.1+1
  image_picker: ^0.6.7+2
  searchable_dropdown: ^1.1.3
  flutter_rating_bar: ^3.0.0
  palette_generator: ^0.2.0
  url_launcher: ^5.2.5
  shimmer: ^1.0.1 
  toast: ^0.1.5
  #chewie: ^0.9.10
  #smart_select: ^4.0.1 
  datetime_picker_formfield: ^1.0.0
  flutter_signin_button: ^1.0.0 
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  #google_maps_flutter: ^1.0.6
  #geolocator: ^6.1.6
  #location_permissions: ^3.0.0
  #flutter_polyline_points: ^0.2.1
  #webview_flutter: ^1.0.7 
  like_button: ^1.0.4 
  #BLE 통신 모듈
  flutter_blue: ^0.7.3
  flutter_bluetooth_serial: ^0.2.2
  blue_thermal_printer: ^1.1.1
  scoped_model: ^1.1.0
  customtogglebuttons: ^0.0.5
  mask_text_input_formatter: ^1.2.1
  basic_utils: ^2.2.4
  csv: ^4.0.3
  flutter_email_sender: ^2.2.0
  month_picker_dialog: ^0.3.3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0 
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - images/img_not_available.jpeg
    - images/  
    - images/icon/
    - lib/models/country_phone_codes.json
    - assets/icon/launcher_icon.png
    - assets/icon/pin.png
#flutter pub pub run flutter_native_splash:create
#flutter_native_splash:
#  image: "assets/icon/launcher_icon.png"
#  color: "ffffff" 
#z   android_disable_fullscreen: true
# 만드는 명령어 flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/launcher_icon.png"

module:
  androidX: true
